import { IProjectProps } from "./components/layout/Projects";

export const projects: IProjectProps[] = [
  {
    coverImg: "/images/dMind.png",
    repoLink: "https://github.com/AbrarShahriar/dMind-desktop",
    projectLink: "https://sourceforge.net/projects/dmind/",
    projectName: "dMind",
    projectDesc: `A minimalistic yet feature-rich note-taking app I created for myself. I wrote a very basic regex-based custom markdown parser; dMind also has built-in intergration with <a href="https://mermaid.js.org/">Mermaid</a> for a diagrams, <a href="https://katex.org/">Katex</a> for LaTeX-based math expression and a simple text-to-table creation algorithm I wrote (that still needs a LOT of work)`,
    tags: [
      "vanilla js",
      "typescript",
      "desktop app",
      "cross-platform",
      "electron",
    ],
    projectTheme: "light",
  },
  {
    coverImg: "/images/amike.png",
    repoLink: "https://github.com/AbrarShahriar/ami.ke_theme",
    projectLink: "https://amike-theme.netlify.app/",
    projectName: "Ami.ke Theme",
    projectDesc:
      "It's a portfolio website I made for a graphics designer based in Bangladesh. This project has a lot of parts that challenged my skills. But at the end of the day, I learnt a lot and that's what matters right?!",
    tags: ["responsive", "parcel", "animation", "masonary layout"],
    projectTheme: "light",
  },
  {
    coverImg: "/images/amazon-clone.png",
    repoLink: "https://github.com/AbrarShahriar/ami.ke_theme",
    projectLink: "https://e-794bc.web.app/",
    projectName: "Amazon Clone",
    projectDesc: `The Amazon clone from <a href="https://www.youtube.com/channel/UCqrILQNl5Ed9Dz6CGMyvMTQ">Clever Programmer</a> with some of my own twists and touches! For instance, I added complete responsiveness which even the real amaozon website doesn't provide.`,
    tags: [
      "e-commerce",
      "user authentication",
      "bucket functionality",
      "react",
      "responsive",
      "firebase",
    ],
    projectTheme: "dark",
  },
  {
    coverImg: "/images/fb-clone.png",
    repoLink: "https://github.com/AbrarShahriar/facebook-clone",
    projectLink: "https://facebook-clone-adib.netlify.app/",
    projectName: "Facebook Clone",
    projectDesc: `The Facebook clone from <a href="https://www.youtube.com/channel/UCqrILQNl5Ed9Dz6CGMyvMTQ">Clever Programmer</a>. Seems like a lot of clones huh! Part learning a new technology is pattern recognition. Although, I try to add some of my own touches to every clone I do.`,
    tags: [
      "authentication",
      "responsive",
      "crud",
      "react",
      "blazzing fast",
      "firebase",
    ],
    projectTheme: "dark",
  },
  {
    coverImg: "/images/spotify-clone.png",
    repoLink: "https://github.com/AbrarShahriar/spotify-clone",
    projectLink: "https://spotify-clone-sa.netlify.app",
    projectName: "Spotify Clone",
    projectDesc: `The Spotify clone from <a href="https://www.youtube.com/channel/UCqrILQNl5Ed9Dz6CGMyvMTQ">Clever Programmer</a>. This one was quite challenging. Configuring the Spotify API was a real pain. Moreover, making it responsive was quite of a challenge. But hey! challenges makes us grow, right??`,
    tags: ["Spotify API", "modern-ui", "react", "context API", "responsive"],

    projectTheme: "light",
  },
  {
    coverImg: "/images/netflix-clone.jpg",
    repoLink: "https://github.com/AbrarShahriar/netflix-clone/",
    projectLink: "https://netflix-clone-adib.netlify.app",
    projectName: "Netflix Clone",
    projectDesc: `The Netflix clone from <a href="https://www.youtube.com/channel/UCqrILQNl5Ed9Dz6CGMyvMTQ">Clever Programmer</a>. This one was fairly simpler to make as it doesn't have user authentication available right now. Overall, it was a fun build!`,
    tags: ["TMDB API", "responsive", "react"],
    projectTheme: "light",
  },
  {
    coverImg: "/images/fast-shot.png",
    repoLink: "https://github.com/AbrarShahriar/fast-shot",
    projectLink: "https://fast-shot.netlify.app/",
    projectName: "Fast Shot",
    projectDesc: `This is one of my real projects.  I learned a ton while working on this. This one really pushed my boundaries. I also had to do some graphic designing stuff.`,

    tags: ["gsap", "css aniamtion", "responsive", "react"],
    projectTheme: "light",
  },
  {
    coverImg: "/images/airbnb-clone.jpg",
    repoLink: "https://github.com/AbrarShahriar/airbnb-clone",
    projectLink: "https://airbnb-clone-adib.netlify.app",
    projectName: "Airbnb clone",
    projectDesc: `The Airbnb clone from <a href="https://www.youtube.com/channel/UCqrILQNl5Ed9Dz6CGMyvMTQ">Clever Programmer</a>. Yet another clone :). Well, it was fun and I also learned how complex layouts are made. It was a win-win!`,
    tags: ["responsive", "date component", "react"],
    projectTheme: "dark",
  },
];
