import { IProjectProps } from "./components/layout/Projects";

export const projects: IProjectProps[] = [
  {
    coverImg: "/images/mochapi.png",
    repoLink: "https://github.com/AbrarShahriar/mochapi/",
    projectLink: "https://mochapi.abrarshahriar.com/",
    projectName: "MochApi",
    projectDesc: `A Mock API toolkit that you can use to generate, customize, and test API endpoints in seconds with built-in and user-defined custom functions, real-time responses, and seamless integration—without managing a backend.`,
    tags: [
      "nextjs",
      "typescript",
      "shadcn",
      "tailwind",
      "nestjs",
      "user authentication",
    ],
    projectTheme: "light",
  },
  {
    coverImg: "/images/dMind.png",
    repoLink: "https://github.com/AbrarShahriar/dMind-desktop",
    projectLink: "https://sourceforge.net/projects/dmind/",
    projectName: "dMind",
    projectDesc: `A minimalistic yet feature-rich note-taking app I created for myself. I wrote a very basic regex-based custom markdown parser; dMind also has built-in intergration with <a href="https://mermaid.js.org/">Mermaid</a> for a diagrams, <a href="https://katex.org/">Katex</a> for LaTeX-based math expression and a simple text-to-table creation algorithm I wrote (that still needs a LOT of work)`,
    tags: [
      "vanilla js",
      "typescript",
      "desktop app",
      "cross-platform",
      "electron",
    ],
    projectTheme: "light",
  },
  {
    coverImg: "/images/cvly.png",
    repoLink: "https://github.com/AbrarShahriar/cvly",
    projectLink: "https://cvly.abrarshahriar.com/",
    projectName: "CVly",
    projectDesc: `A simple CV making app that is completely client-side, no hidden paywalls! I wanted a simple CV making tool that was simple to use and didn't require any extra skilss, sign-ups or payment. Hence, I created CVly - fill in your information, pick a template and download a ready-made ATS-friendly CV.`,
    tags: ["nextjs", "typescript", "shadcn", "tailwind", "react-pdf"],
    projectTheme: "dark",
  },
  {
    coverImg: "/images/amike.png",
    repoLink: "https://github.com/AbrarShahriar/ami.ke_theme",
    projectLink: "https://amike-theme.netlify.app/",
    projectName: "Ami.ke Theme",
    projectDesc:
      "It's a portfolio website I made for a graphics designer based in Bangladesh. This project has a lot of parts that challenged my skills. But at the end of the day, I learnt a lot and that's what matters right?!",
    tags: ["responsive", "parcel", "animation", "masonary layout"],
    projectTheme: "light",
  },
  {
    coverImg: "/images/amazon-clone.png",
    repoLink: "https://github.com/AbrarShahriar/ami.ke_theme",
    projectLink: "https://e-794bc.web.app/",
    projectName: "Amazon Clone",
    projectDesc: `The Amazon clone from <a href="https://www.youtube.com/channel/UCqrILQNl5Ed9Dz6CGMyvMTQ">Clever Programmer</a> with some of my own twists and touches! For instance, I added complete responsiveness which even the real amaozon website doesn't provide.`,
    tags: [
      "e-commerce",
      "user authentication",
      "bucket functionality",
      "react",
      "responsive",
      "firebase",
    ],
    projectTheme: "dark",
  },

  {
    coverImg: "/images/fast-shot.png",
    repoLink: "https://github.com/AbrarShahriar/fast-shot",
    projectLink: "https://fast-shot.netlify.app/",
    projectName: "Fast Shot",
    projectDesc: `This is one of my real projects.  I learned a ton while working on this. This one really pushed my boundaries. I also had to do some graphic designing stuff.`,

    tags: ["gsap", "css aniamtion", "responsive", "react"],
    projectTheme: "light",
  },
  {
    coverImg: "/images/airbnb-clone.jpg",
    repoLink: "https://github.com/AbrarShahriar/airbnb-clone",
    projectLink: "https://airbnb-clone-adib.netlify.app",
    projectName: "Airbnb clone",
    projectDesc: `The Airbnb clone from <a href="https://www.youtube.com/channel/UCqrILQNl5Ed9Dz6CGMyvMTQ">Clever Programmer</a>. Yet another clone :). Well, it was fun and I also learned how complex layouts are made. It was a win-win!`,
    tags: ["responsive", "date component", "react"],
    projectTheme: "dark",
  },
];
